config/routes.rb
 

InventarTool::Application.routes.draw do
  root :to => "dashboard#index"
  match 'search', :to => 'search#index'
  match 'warranty', :to => 'warranty#index'
  match 'dashboard', :to => 'dashboard#index'
  match 'repository', :to => 'repository#index'

  get "dashboard/index"
  get "warranty/index"
  get "repository/index"
  post "repository/attach"
  post "search/search"

resources :servers, :notebooks, :disks, :rams, :displays, :distributors, :owners, :stock_objects do
  collection do
    get 'removed'
  end
  member do
    get 'restore'
  end
end

resources :disks, :rams do
  member do
    get 'detach'
  end
end

resources :servers, :notebooks do
  member do
    get 'unuse'
  end
end

resource :repository, :search

end

app/controllers/dashboard_controller.rb
#  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 

class DashboardController < CrudController
  def index
    @title = "InventarTool Dashboard"
    @user_name = session[:user_name]
    @user_uid = session[:user_ui]
    
  end

end

app/helpers/dashboard_helper.rb
#  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 

module DashboardHelper
end

app/views/dashboard/index.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<div id="user">Angemeldet als: <%= @user_name + " (" + @user_uid + ")"%></div>
<div id="dashboard">
  <div id="dashboard_1" class="division" >
    <div>
      <h2>Servers</h2>
      <ul>
        <li><%= link_to "List Servers", servers_path%></li>
        <li><%= link_action('New Server', 'add', 'servers/new', {}) %></li>
      </ul>
      
    </div>
    <div>
      <h2>Notebooks</h2>
      <ul>
        <li><%= link_to "List Notebooks", notebooks_path%></li>
        <li><%= link_action('New Notebook', 'add', 'notebooks/new', {}) %></li>
      </ul>
    </div>
    <div>
      <h2>Displays</h2>
      <ul>
        <li><%= link_to "List Displays", displays_path%></li>
        <li><%= link_action('New Display', 'add', 'displays/new', {}) %></li>
      </ul>
    </div>
  </div>
  
  <div id="dashboard_2" class="division" >
    <div>
      <h2>Disks</h2>
      <ul>
        <li><%= link_to "List Disks", disks_path%></li>
        <li><%= link_action('New Disk', 'add', 'disks/new', {}) %></li>
      </ul>
    </div>
    
    <div>
      <h2>Rams</h2>
      <ul>
        <li><%= link_to "List Rams", rams_path%></li>
        <li><%= link_action('New Ram', 'add', 'rams/new', {}) %></li>
      </ul>
    </div>

    <div>
      <h2>Owners</h2>
      <ul>
        <li><%= link_to "List Owners", owners_path%></li>
        <li><%= link_action('New Owner', 'add', 'owners/new', {}) %></li>
      </ul>
    </div>
    
    <div>
      <h2>Distributors</h2>
      <ul>
        <li><%= link_to "List Distributors", distributors_path%></li>
        <li><%= link_action('New Distributor', 'add', 'distributors/new', {}) %></li>
      </ul>
    </div>
  </div>
  
  <div id="dashboard_3" class="division" >
    <div>
      <h2>Stock</h2>
      <ul>
        <li><%= link_to "Manage Stock", stock_objects_path%></li>
      </ul>
    </div>
      
    <div>
      <h2>Warranty</h2>
      <ul>
        <li><%= link_to "Warranty Ends", :warranty %></li>
      </ul>
    </div>

    <div>
      <h2>Search</h2>
      <ul>
        <li><%= link_to "Search", :search %></li>
      </ul>
    </div>
  </div>
</div>