config/routes.rb
 

InventarTool::Application.routes.draw do
  root :to => "dashboard#index"
  match 'search', :to => 'search#index'
  match 'warranty', :to => 'warranty#index'
  match 'dashboard', :to => 'dashboard#index'
  match 'repository', :to => 'repository#index'

  get "dashboard/index"
  get "warranty/index"
  get "repository/index"
  post "repository/attach"
  post "search/search"

resources :servers, :notebooks, :disks, :rams, :displays, :distributors, :owners, :stock_objects do
  collection do
    get 'removed'
  end
  member do
    get 'restore'
  end
end

resources :disks, :rams do
  member do
    get 'detach'
  end
end

resources :servers, :notebooks do
  member do
    get 'unuse'
  end
end

resource :repository, :search

end

app/models/notebook.rb
#  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 

class Notebook < ActiveRecord::Base
  belongs_to :distributor
  belongs_to :owner
  
  acts_as_versioned
  
  has_many :disks, :as => :machine
  has_many :rams, :as => :machine
  
  scope :removed, where(:removed => true)
  scope :not_removed, where(:removed => (nil or false))
  default_scope :order => 'model, service_tag'
  
  def label
    "#{model}"
  end
  
  def age_in_days
    Date.today - purchase_date
  end
  
  def warranty_end_in_days
      warranty_till - Date.today
  end
  
  def attrs_list
    [:model, :processor, :serial_number]
  end
  def self.list_columns
    [:model, :owner, :service_tag]
  end
end

app/controllers/notebooks_controller.rb
#  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 

class NotebooksController < CrudController
  #Remove Module
  require 'modules/remove_module.rb'
  include Remove
  define_model_callbacks :render_removed
  
  # Versions Module
  require 'modules/versions_module.rb'
  include Versions
  before_render_show :set_diffhash
  before_save :set_creator
  
  self.search_columns = [:model, :processor, :serial_number, :service_tag, :express_service_code, :previous_owner, :notes, :battery_serial_number, :power_supply_serial_number, :mac_addr_lan, :mac_addr_wlan]
  
  before_filter :set_warranty, :only => [:update, :create]
  before_render_form :set_values
  
  def set_warranty
    @warranty_till = (params[model_identifier][:warranty_till]).to_i
    @purchase_date = Date.parse((params[model_identifier][:purchase_date]))
    # @purchase_date = Date.parse( {"1i"=>params[model_identifier][:"purchase_date(1i)"], "2i"=>params[model_identifier][:"purchase_date(2i)"], "3i"=>params[model_identifier][:"purchase_date(3i)"]}.to_a.sort.collect{|c| c[1]}.join("-"))
    params[model_identifier][:warranty_till] = @purchase_date + @warranty_till.years
  end
  
  def set_values
    @entry.purchase_date ||= Date.today
    @entry.warranty_till ||= Date.today
    if (@entry.warranty_till != nil)
      @entry.warranty_till = ((@entry.warranty_till - @entry.purchase_date).to_i)/365
    end
  end
  
  def unuse
    set_entry
    puts @entry.inspect
    @entry.distributor = nil
    detached = save_entry
    redirect_to :back
  end
  
end

app/helpers/notebooks_helper.rb
#  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 

module NotebooksHelper
end

app/views/notebooks/_edit_used.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<h3><%=pluralize(@entry.notebooks.count, "notebook")%> used</h3>
<ul>
<% @entry.notebooks.each do |n| %>
<li><%= link_to "#{n.model} #{n.serial_number}", notebooks_path(n.id) %> | <%= link_action 'unuse', 'delete', url_options = {:controller => 'notebooks', :id => n.id, :action => 'unuse'}, :confirm => "Are you sure?" %></li>
<% end %>
</ul>
<%= link_action 'Add notebook', 'add', notebooks_path %>

app/views/notebooks/_form.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<%= crud_form(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this ram from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.labeled_input_fields :model, :processor, :serial_number, :service_tag, :express_service_code, :price, :purchase_date%>
  <div class="labeled">
    <div class="caption"><%= f.label :warranty_duration %></div>
    <div class="value"><%= f.text_field :warranty_till %></div>
  </div>
  <%= f.labeled_input_fields :owner_changed_on, :previous_owner, :battery_serial_number, :power_supply_serial_number, :mac_addr_lan, :mac_addr_wlan, :notes, :in_repair, :distributor_id, :owner_id, :change_notice%>
<%end%>

app/views/notebooks/_used.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<h3><%=pluralize(@entry.notebooks.count, "notebook")%> used</h3>
<ul>
<% @entry.notebooks.each do |n| %>
<li><%= link_to "#{n.model} #{n.serial_number}", notebook_path(n.id) %></li>
<% end %>
</ul>

app/views/notebooks/edit.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<% @title ||= "Edit #{full_entry_label}" -%>

<% content_for(:actions, render(:partial => 'actions_edit')) %>

<%= clear %>

<%= render :partial => 'form' %>
<%= render :partial => 'rams/edit_attached' %>
<%= render :partial => 'disks/edit_attached' %>

app/views/notebooks/show.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<% @title ||= full_entry_label -%>

<% content_for(:actions, render(:partial => 'actions_show')) %>

<%= clear %>
<%= render :partial => 'attrs' %>
<%= render :partial => 'attrs_warranty' %>

<%= render :partial => 'rams/attached' %>
<%= render :partial => 'disks/attached' %>

<%= render :partial => 'versions' %>