config/routes.rb
 

InventarTool::Application.routes.draw do
  root :to => "dashboard#index"
  match 'search', :to => 'search#index'
  match 'warranty', :to => 'warranty#index'
  match 'dashboard', :to => 'dashboard#index'
  match 'repository', :to => 'repository#index'

  get "dashboard/index"
  get "warranty/index"
  get "repository/index"
  post "repository/attach"
  post "search/search"

resources :servers, :notebooks, :disks, :rams, :displays, :distributors, :owners, :stock_objects do
  collection do
    get 'removed'
  end
  member do
    get 'restore'
  end
end

resources :disks, :rams do
  member do
    get 'detach'
  end
end

resources :servers, :notebooks do
  member do
    get 'unuse'
  end
end

resource :repository, :search

end

app/models/disk.rb
#  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 

class Disk < ActiveRecord::Base
  belongs_to :distributor
  belongs_to :machine, :polymorphic => true
  
  acts_as_versioned :table_name => :disk_versions
  
  scope :removed, where(:removed => true)
  scope :not_removed, where(:removed => (nil or false))
  default_scope :order => 'disks.model ASC'
  
  def label
    "#{model}"
  end
  
  def age_in_days
    (Date.today - purchase_date)
  end
  
  def warranty_end_in_days
    (warranty_till - Date.today)
  end

  def attrs_list
    [:model, :capacity, :serial_number]
  end
  def self.list_columns
    [:model, :capacity, :serial_number, :machine, :distributor]
  end
  
end

app/controllers/disks_controller.rb
#  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 

class DisksController < CrudController
  #Remove Module
  require 'modules/remove_module.rb'
  include Remove
  define_model_callbacks :render_removed
  
  # Versions Module
  require 'modules/versions_module.rb'
  include Versions
  before_render_show :set_diffhash
  before_save :set_creator


  self.search_columns = [:model, :serial_number, :notes, :capacity]
  
  before_filter :set_machine, :set_change_notice, :set_warranty, :only => [:update, :create]
  
  before_render_form :set_values
  
  def set_values
    @entry.purchase_date ||= Date.today
    @entry.warranty_till ||= Date.today
    @a_machines = []
    @a_machines << ["(none)", nil ]
    Notebook.all.each do |machine|
      @a_machines << ["Notebook: #{machine.label} #{machine.service_tag}", "Notebook_#{machine.id}"]
    end
    Server.all.each do |machine|
      @a_machines << ["Server: #{machine.label}", "Server_#{machine.id}"]
    end
    
    if (@entry.warranty_till != nil)
      @entry.warranty_till = ((@entry.warranty_till - @entry.purchase_date).to_i)/365
    end
  end

  def set_machine
    m = params[model_identifier].delete(:machine).split("_")
    @entry.machine_type = m[0]
    @entry.machine_id = m[1]
  end
  def set_change_notice
    if (params[model_identifier][:change_notice] == "")
      params[model_identifier][:change_notice] = @entry.change_notice
    end
  end
  
  def set_warranty
    @warranty_till = (params[model_identifier][:warranty_till]).to_i
    @purchase_date = Date.parse((params[model_identifier][:purchase_date]))
    # purchase_date = Date.parse( {"1i"=>params[model_identifier][:"purchase_date(1i)"], "2i"=>params[model_identifier][:"purchase_date(2i)"], "3i"=>params[model_identifier][:"purchase_date(3i)"]}.to_a.sort.collect{|c| c[1]}.join("-"))
    params[model_identifier][:warranty_till] = @purchase_date + @warranty_till.years
  end
  
  def detach
    set_entry
    @entry.machine_id = nil
    @entry.machine_type = nil
    success = save_entry
    message = "detached"
    respond_processed(success, message ) do |format|
      format.html do 
        if success
          request.env["HTTP_REFERER"].present? ? redirect_to(:back) : redirect_to_show
        else
          flash.alert = @entry.errors.full_messages.join('<br/>').html_safe
          request.env["HTTP_REFERER"].present? ? redirect_to(:back) : redirect_to_show
        end
      end
    end
  end
  
  def unuse
    set_entry
    puts @entry.inspect
    @entry.distributor = nil
    detached = save_entry
    redirect_to :back
  end
  
end

app/helpers/disks_helper.rb
#  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 

module DisksHelper
  def format_capacity(disk)
    "#{disk.capacity} GB"
  end
end

app/views/disks/_attached.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<h3><%=pluralize(@entry.disks.count, "disk")%> attached</h3>
<ul>
<% @entry.disks.each do |d| %>
<li><%= link_to "#{d.model} #{d.capacity}GB", disk_path(d.id) %></li>
<% end %>
</ul>

app/views/disks/_edit_attached.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<h3><%=pluralize(@entry.disks.count, "disk")%> attached</h3>
<ul>
<% @entry.disks.each do |d| %>
<li><%= link_to "#{d.model} #{d.capacity}GB", disk_path(d.id)%> |
  <%= link_action 'detach', 'delete', url_options = {:controller => 'disks', :id => d.id, :action => 'detach'}, :confirm => "Are you sure?" %>
  <%= link_to "Same Disks", disks_path + "?utf8=✓&returning=true&q=" + (d.model).to_s, :target=>"_blank"%>
</li>
<% end %>
</ul>
<%= link_action 'Add disk', 'add', :controller => "repository", :id => "#{@entry.id}", :machine_type => "#{model_class.table_name}", :entry => "disk"%>

app/views/disks/_form.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<%= crud_form(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this ram from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= f.labeled_input_fields :model, :serial_number, :purchase_date %>
  <div class="labeled">
    <div class="caption"><%= f.label :warranty_duration %></div>
    <div class="value"><%= f.text_field :warranty_till %></div>
  </div>
  <%= f.labeled_input_fields :price, :notes, :capacity, :connector, :distributor_id, :in_repair %>
  <div class="labeled">
    <div class="caption"><%= f.label :machine %></div>
    <div class="value"><%= f.select(:machine, @a_machines, {:selected => "#{@entry.machine_type}_#{@entry.machine_id}", :prompt => 'Select Machine'}) %></div>
  </div>
  <%= f.labeled_input_fields :change_notice%>
<% end %>

app/views/disks/_versions.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<h2>Changes:</h2>
<% @diffary.each do |version_hash| %>
  <%number = version_hash[:version]; version = version_hash[:diff] %>
  <table class="version" >
  <tr><td colspan="3"><%= "version #{number} by #{version.delete(:creator)} on #{version.delete(:updated_at).strftime("%A, %Y-%m-%d %H:%M")}" %></td></tr>
  <tr><td class="key">Notice: </td><td colspan="2"><%= "#{version.delete(:change_notice)}" %></td></tr>
  	<% version.each do |key, c| %>
  		<tr>
  			<td class="key"><%= key %></td>
  			<td><%= c[0] %></td>
  			<td><%= c[1]%></td>
  		</tr>
  	<% end %>
  </table>
  <br>
<% end %>
<%= will_paginate @diffary %>
<br>

app/views/disks/show.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<% @title ||= full_entry_label -%>

<% content_for(:actions, render(:partial => 'actions_show')) %>

<%= clear %>

<%= render :partial => 'attrs' %>
<%= render :partial => 'attrs_warranty' %>

<%= render :partial => 'versions' %>