config/routes.rb
 

InventarTool::Application.routes.draw do
  root :to => "dashboard#index"
  match 'search', :to => 'search#index'
  match 'warranty', :to => 'warranty#index'
  match 'dashboard', :to => 'dashboard#index'
  match 'repository', :to => 'repository#index'

  get "dashboard/index"
  get "warranty/index"
  get "repository/index"
  post "repository/attach"
  post "search/search"

resources :servers, :notebooks, :disks, :rams, :displays, :distributors, :owners, :stock_objects do
  collection do
    get 'removed'
  end
  member do
    get 'restore'
  end
end

resources :disks, :rams do
  member do
    get 'detach'
  end
end

resources :servers, :notebooks do
  member do
    get 'unuse'
  end
end

resource :repository, :search

end

app/models/display.rb
#  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 

class Display < ActiveRecord::Base
  belongs_to :distributor
  belongs_to :owner
  
  acts_as_versioned
  
  scope :removed, where(:removed => true)
  scope :not_removed, where(:removed => (nil or false))
  default_scope :order => 'model, serial_number'
  
  def label
    "#{model}"
  end
  
  def attrs_list
    [:model, :serial_number]
  end
  def self.list_columns
    [:model, :serial_number, :owner, :distributor]
  end
end

app/controllers/displays_controller.rb
#  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 

class DisplaysController < CrudController
  #Remove Module
  require 'modules/remove_module.rb'
  include Remove
  define_model_callbacks :render_removed
  
  # Versions Module
  require 'modules/versions_module.rb'
  include Versions
  before_render_show :set_diffhash
  before_save :set_creator
  before_render_form :set_values
  
  self.search_columns = [:model, :serial_number, :notes]
  
  def set_values
    @entry.purchase_date ||= Date.today
  end
  
  def unuse
    set_entry
    puts @entry.inspect
    @entry.distributor = nil
    detached = save_entry
    redirect_to :back
  end
  
end

app/helpers/displays_helper.rb
#  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 

module DisplaysHelper
end

app/views/displays/_edit_used.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<h3><%=pluralize(@entry.displays.count, "display")%> used</h3>
<ul>
<% @entry.displays.each do |d| %>
<li><%= link_to "#{d.model} #{d.serial_number}", displays_path(d.id) %> | <%= link_action 'unuse', 'delete', url_options = {:controller => 'displays', :id => d.id, :action => 'unuse'}, :confirm => "Are you sure?" %></li>
<% end %>
</ul>
<%= link_action 'Add display', 'add', displays_path %>

app/views/displays/_used.html.erb
<% #  | # COPYRIGHT HEADER START # 
# |   InventarTool - Web Application to manage hardware and components inventory
# |   Copyright (C) 2011  Puzzle ITC GmbH www.puzzle.ch
# |   
# |   This program is free software: you can redistribute it and/or modify
# |   it under the terms of the GNU Affero General Public License as
# |   published by the Free Software Foundation, either version 3 of the
# |   License, or (at your option) any later version.
# |   
# |   This program is distributed in the hope that it will be useful,
# |   but WITHOUT ANY WARRANTY; without even the implied warranty of
# |   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# |   GNU Affero General Public License for more details.
# |   
# |   You should have received a copy of the GNU Affero General Public License
# |   along with this program.  If not, see <http://www.gnu.org/licenses/>.
# | # COPYRIGHT HEADER END # 
 %> 

<h3><%=pluralize(@entry.displays.count, "display")%> used</h3>
<ul>
<% @entry.displays.each do |d| %>
<li><%= link_to "#{d.model} #{d.serial_number}", display_path(d.id) %></li>
<% end %>
</ul>